Repository specify/specify7, pull requests merged in 2024-06, with the labels that each got.

#4724 Add group number support in Taxon queries
  specifyweb/frontend/js_src/lib/components/WbPlanView/navigator.ts
  specifyweb/stored_queries/queryfieldspec.py
Labels: 2 - Trees, 2 - Queries

#4968 Handle unassigned fields in preparation when calculating fields
  specifyweb/specify/calculated_fields.py
Labels: 1 - Bug

#5010 Add length attribute to Calendar fields in datamodel
  specifyweb/specify/load_datamodel.py
  specifyweb/specify/serialize_datamodel.py
  specifyweb/workbench/upload/parsing.py
Labels: 2 - Queries
